x

diff --git a/fmrc b/fmrc
--- a/fmrc
+++ b/fmrc
@@ -1,13 +1,62 @@
+interval=4
+ncams=3
+
+switchdur=350
+codecargs="-codec mpeg4"
 seglen=600
+
+muxerargs="-f segment -segment_time ${seglen:?} -strftime 1"
+muxerargs=
+
+fontfile="/usr/share/fonts/TTF/DejaVuSans.ttf"
+
+testbox="drawtext=fontfile=${fontfile:?}: boxcolor=0x000000AA:box=1:y=line_h:fontsize=72:fontcolor='white':text='%{e\:gte(st(0,mod(time(0)*1000,3*4*1000)),0*4*1000)*lt(ld(0),(0+1)*4*1000)}'"
+stampbox="drawtext=fontfile=${fontfile:?}: boxcolor=0x000000AA:box=1:fontsize=72:fontcolor='white':text='%{localtime\:%T}.%{eif\:mod(time(0)*1000,1000)\:d\:3}'"
+
 shopt -s nullglob
+
+fm_mycycle_start() {
+    $THISDIR/mycycle >/dev/null &
+    fm_mycycle_pid=$!
+}
+
+fm_mycycle_stop() {
+    if [ -n "${ffmpeg_pid}" ]; then
+        kill -TERM ${fm_mycycle_pid:?} 2>/dev/null || true
+        fm_mycycle_pid=
+    fi
+}
+
+fm_killffmpeg() {
+    if [ -n "${ffmpeg_pid}" ]; then
+        kill -TERM "${ffmpeg_pid:?}" 2>/dev/null || true
+        ffmpeg_pid=
+    fi
+}
+
+fm_killwdog() {
+    if [ -n "${ffmpeg_watchdog_pid}" ]; then
+        kill -TERM "${ffmpeg_watchdog_pid:?}" 2>/dev/null || true
+        ffmpeg_watchdog_pid=
+    fi
+}
 
 fm_record_in_empty_dirs() {
     local station i subdir have
+    ffmpeg_pid=
+    fm_mycycle_pid=
+    ffmpeg_watchdog_pid=
+
     station=${1:?}
     shift
 
     subdir="$station"
     mkdir -p "${subdir:?}/`date +%Y%m%d`" "${subdir:?}/`date --date=tomorrow +%Y%m%d`"
+
+    if [ "x$1" = x"fm_rec_cam" ]; then
+        fm_mycycle_start
+    fi
+    trap 'fm_mycycle_stop; fm_killffmpeg; fm_killwdog;' EXIT
 
     while true; do
         echo "writing to $subdir"
@@ -34,7 +83,7 @@ fm_ffmpeg_watchdog() {
             echo
             echo "ffmpeg seems hung"
             echo
-            fm_killffmpeg "$ffmpeg_pid"
+            fm_killffmpeg
             break
         fi
         prevstate=$newstate
@@ -44,7 +93,6 @@ fm_ffmpeg_watchdog() {
 
 fm_ffmpeg() {
     rc=1
-    local ffmpeg_pid ffmpeg_watchdog_pid
     echo ffmpeg "$@"
     ffmpeg "$@" &
     ffmpeg_pid=$!
@@ -57,32 +105,33 @@ fm_ffmpeg() {
 
     rc=0
     wait $ffmpeg_pid || rc=$?
-    kill -KILL $ffmpeg_watchdog_pid 2>/dev/null
-}
-
-fm_killffmpeg() {
-    local ffmpeg_pid
-
-    ffmpeg_pid=${1:?}
-    kill -TERM $ffmpeg_pid
+    fm_killwdog
 }
 
 fm_rec_cam() {
-    fm_ffmpeg -loglevel warning -y \
-        -f video4linux2 -i /dev/video0 \
-        -filter_complex "
-        [0:v]select='gte(st(0,mod(time(0)*1000,${ncams:?}*${interval:?}*1000)),2*${interval:?}*1000+300)*lt(ld(0),(2+1)*${interval:?}*1000-1)',${stampbox:?},fifo[out2];
-        [0:v]select='gte(st(0,mod(time(0)*1000,${ncams:?}*${interval:?}*1000)),1*${interval:?}*1000+300)*lt(ld(0),(1+1)*${interval:?}*1000-1)',${stampbox:?},fifo[out1];
-        [0:v]select='gte(st(0,mod(time(0)*1000,${ncams:?}*${interval:?}*1000)),0*${interval:?}*1000+300)*lt(ld(0),(0+1)*${interval:?}*1000-1)',${stampbox:?},fifo[out0]
-        " \
-        -map '[out2]' -codec mpeg4 -f segment -segment_time $seglen -strftime 1 "${subdir:?}/%Y%m%d/split2-%H-%M-%S.mkv" \
-        -map '[out1]' -codec mpeg4 -f segment -segment_time $seglen -strftime 1 "${subdir:?}/%Y%m%d/split1-%H-%M-%S.mkv" \
-        -map '[out0]' -codec mpeg4 -f segment -segment_time $seglen -strftime 1 "${subdir:?}/%Y%m%d/split0-%H-%M-%S.mkv"
+    local i filterstr= outmap=()
+
+    for ((i=0; i<ncams; i++)); do
+        filterstr="${filterstr}${filterstr:+;}
+        [0:v]select='gte(st(0,mod(time(0)*1000,${ncams:?}*${interval:?}*1000)),$i*${interval:?}*1000+${switchdur:?})*lt(ld(0),($i+1)*${interval:?}*1000-1)',${stampbox:?}[out$i]"
+        outmap+=(-map "[out$i]" $codecargs $muxerargs "${subdir:?}/%Y%m%d/split$i-%H-%M-%S.mkv")
+    done
+
+# ,fps=25,fifo
+    fm_ffmpeg -loglevel warning -y -f video4linux2 -i /dev/video0 -filter_complex "$filterstr" "${outmap[@]}"
 }
 
 fm_all() {
     [ $# = 0 ] && set -- cam
     for st in "$@"; do
-        fm_record_in_empty_dirs $st fm_rec_$st &
+        fm_record_in_empty_dirs $st fm_rec_$st
     done
+}
+
+fm_resetup() {
+    set -e
+    set -o pipefail
+    function errtrap {     es=$?;     echo "ERROR line $1: Command exited with status $es.">&2; }; trap 'errtrap $LINENO' ERR
+    
+    THISDIR=`cd "\`dirname \"${BASH_SOURCE[0]}\"\`" && pwd`
 }
